/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wlutqenwyfphumbmxqni"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsdXRxZW53eWZwaHVtYm14cW5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA1MTkzNjUsImV4cCI6MjA4NjA5NTM2NX0.rxShfnmFPX1yGy6FJdeZWpKo4-6CC2cFI-JtGSIa2y4"